#!/bin/bash

###########################
# CLI for mac music apps #
#########################

SCRIPTNAME="Music"

function usage() {
    printf "Usage of $SCRIPTNAME:\n"
    printf "\n"
    printf "Options:\n"
    printf "play, plays your music\n"
    printf "pause, pauses your music\n"
}

SPOTIFY="Spotify"
ITUNES="iTunes"

if [[ ${1} = play ]]; then
    osascript play.applescript
elif [[ ${1} = pause ]]; then
    osascript pause.applescript
elif [[ ${1} = help ]]; then
    usage
else
    exit 1
fi
exit 0
